/*
 * File: app/view/laboresForm.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.laboresForm', {
    extend: 'Ext.container.Container',
    alias: 'widget.laboresform',

    requires: [
        'MyApp.view.establecimientosGridViewModel14',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.tab.Bar',
        'Ext.toolbar.Toolbar'
    ],

    viewModel: {
        type: 'laboresform'
    },
    id: 'formpanel',
    itemId: 'formpanel',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'tabpanel',
            flex: 1,
            flex: 1,
            id: 'tabPanelLabores',
            itemId: 'tabPanelLabores',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    scrollable: 'true',
                    title: 'Lab',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    tabConfig: {
                        xtype: 'tab',
                        scrollable: 'true',
                        iconAlign: 'bottom'
                    },
                    items: [
                        {
                            xtype: 'form',
                            flex: 1,
                            itemId: 'form',
                            scrollable: 'true',
                            bodyPadding: 10,
                            glyph: 'xf234@FontAwesome',
                            title: 'Labores',
                            items: [
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    height: 40,
                                    itemId: 'fecha',
                                    padding: '10 5 10 5',
                                    fieldLabel: '',
                                    editable: false,
                                    emptyText: 'Fecha',
                                    format: 'd/m/Y'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    height: 40,
                                    itemId: 'tareaLaboresCbo',
                                    padding: '10 5 10 5',
                                    fieldLabel: '',
                                    name: 'cod_tarea',
                                    editable: false,
                                    emptyText: 'Tarea',
                                    autoLoadOnValue: true,
                                    displayField: 'descripcion',
                                    store: 'TareasMysql',
                                    valueField: 'id'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    height: 40,
                                    padding: '10 5 10 5',
                                    fieldLabel: '',
                                    name: 'cantidad',
                                    editable: false,
                                    emptyText: 'Cantidad'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    height: 40,
                                    padding: '10 5 10 5',
                                    fieldLabel: '',
                                    name: 'precio',
                                    inputType: 'number',
                                    emptyText: 'Precio'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    height: 40,
                                    padding: '10 5 10 5',
                                    fieldLabel: '',
                                    name: 'cod_contratista',
                                    editable: false,
                                    emptyText: 'Contratista',
                                    displayField: 'nombre',
                                    store: 'ContratistasMysql',
                                    valueField: 'codigo'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    scrollable: 'true',
                    title: 'Ins',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    tabConfig: {
                        xtype: 'tab',
                        scrollable: 'true',
                        iconAlign: 'bottom'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'accordion',
                                collapseFirst: false
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    animCollapse: true,
                                    collapsed: true,
                                    collapsible: true,
                                    glyph: 'xf043@FontAwesome',
                                    hideCollapseTool: true,
                                    title: 'Insumos',
                                    titleAlign: 'left',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            flex: 1,
                                            scrollable: 'true',
                                            header: false,
                                            title: 'My Grid Panel',
                                            autoLoad: true,
                                            forceFit: true,
                                            store: 'Labores_insumos',
                                            columns: [
                                                {
                                                    xtype: 'numbercolumn',
                                                    renderer: function(value, record, rowIndex) {
                                                        var store = Ext.getStore('InsumosMysql');
                                                        console.log(value);
                                                        var num = store.find('codigo',value);
                                                        if (num==-1) {return '...';}
                                                        else { return store.getAt(num).get('descripcion');}
                                                    },
                                                    dataIndex: 'cod_insumo',
                                                    text: 'Cod Insumo',
                                                    format: '00'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'dosis',
                                                    text: 'Dosis',
                                                    format: '00'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'cantidad',
                                                    text: 'Cantidad',
                                                    format: '00'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    renderer: function(value, record, rowIndex) {
                                                        console.log(value);
                                                        var store = Ext.getStore('DepositosMysql');
                                                        var num = store.find('codigo',value);
                                                        console.log(num);
                                                        if (num==-1) {return '...';}
                                                        else { return store.getAt(num).get('nombre');}
                                                    },
                                                    dataIndex: 'cod_deposito',
                                                    text: 'Cod Deposito',
                                                    format: '0'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    itemId: 'nuevoInsumoPnl',
                                    animCollapse: true,
                                    collapseFirst: false,
                                    collapsed: true,
                                    collapsible: true,
                                    glyph: 'xf055@FontAwesome',
                                    hideCollapseTool: true,
                                    iconAlign: 'right',
                                    title: 'Nuevo Insumo',
                                    titleAlign: 'right',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            flex: 0,
                                            itemId: 'insDescrip',
                                            padding: '10px 20px',
                                            fieldLabel: '',
                                            editable: false,
                                            emptyText: 'Insumo',
                                            displayField: 'descripcion',
                                            store: 'InsumosMysql',
                                            valueField: 'codigo'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            flex: 0,
                                            itemId: 'insCant',
                                            padding: '10px 20px',
                                            fieldLabel: '',
                                            editable: false,
                                            emptyText: 'Cantidad'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 0,
                                            itemId: 'insDosis',
                                            padding: '10px 20px',
                                            fieldLabel: '',
                                            editable: false,
                                            emptyText: 'Dosis'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 0,
                                            itemId: 'insDeposito',
                                            padding: '10px 20px',
                                            fieldLabel: '',
                                            editable: false,
                                            emptyText: 'Deposito',
                                            displayField: 'nombre',
                                            store: 'DepositosMysql',
                                            valueField: 'codigo'
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 0,
                                            margin: '',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    flex: 0,
                                                    flex: 0,
                                                    itemId: 'aceptaInsumoLab',
                                                    margin: '0px 10px',
                                                    text: 'Guardar'
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 0,
                                                    flex: 0,
                                                    margin: '0px 10px',
                                                    text: 'Cancelar'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    scrollable: 'true',
                    title: 'Pers',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    tabConfig: {
                        xtype: 'tab',
                        scrollable: 'true',
                        iconAlign: 'bottom'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'accordion',
                                collapseFirst: false
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    animCollapse: true,
                                    collapsed: true,
                                    collapsible: true,
                                    glyph: 'xf0c0@FontAwesome',
                                    hideCollapseTool: true,
                                    title: 'Personal',
                                    titleAlign: 'left',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            flex: 1,
                                            scrollable: 'true',
                                            header: false,
                                            title: 'My Grid Panel',
                                            autoLoad: true,
                                            forceFit: true,
                                            store: 'Labores_personal',
                                            columns: [
                                                {
                                                    xtype: 'numbercolumn',
                                                    renderer: function(value, record, rowIndex) {
                                                        var store = Ext.getStore('PersonalMysql');
                                                        var num = store.find('codigo',value);
                                                        console.log(num);
                                                        if (num==-1) {return '...';}
                                                        else { return store.getAt(num).get('nombre');}
                                                    },
                                                    dataIndex: 'cod_empleado',
                                                    text: 'Cod Empleado',
                                                    format: '00'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'cantidad',
                                                    text: 'Cantidad',
                                                    format: '0'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'precio',
                                                    text: 'Precio'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'importe',
                                                    text: 'Importe'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    itemId: 'nuevoPersonaPnl',
                                    animCollapse: true,
                                    collapseFirst: false,
                                    collapsed: true,
                                    collapsible: true,
                                    glyph: 'xf055@FontAwesome',
                                    hideCollapseTool: true,
                                    iconAlign: 'right',
                                    title: 'Nuevo Personal',
                                    titleAlign: 'right',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            flex: 0,
                                            itemId: 'personalPer',
                                            padding: '10px 20px',
                                            fieldLabel: '',
                                            editable: false,
                                            emptyText: 'Personal',
                                            displayField: 'nombre',
                                            store: 'PersonalMysql',
                                            valueField: 'codigo'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            flex: 0,
                                            itemId: 'cantidadPer',
                                            padding: '10px 20px',
                                            fieldLabel: '',
                                            editable: false,
                                            emptyText: 'Cantidad'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 0,
                                            itemId: 'precioPer',
                                            padding: '10px 20px',
                                            fieldLabel: '',
                                            inputType: 'number',
                                            emptyText: 'Precio'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 0,
                                            itemId: 'importePer',
                                            padding: '10px 20px',
                                            fieldLabel: '',
                                            inputType: 'number',
                                            editable: false,
                                            emptyText: 'Importe'
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 0,
                                            margin: '',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    flex: 0,
                                                    flex: 0,
                                                    itemId: 'aceptaPerLabBtn',
                                                    margin: '0px 10px',
                                                    text: 'Guardar'
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 0,
                                                    flex: 0,
                                                    margin: '0px 10px',
                                                    text: 'Cancelar'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    scrollable: 'true',
                    title: 'Maq',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    tabConfig: {
                        xtype: 'tab',
                        scrollable: 'true',
                        iconAlign: 'bottom'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'accordion',
                                collapseFirst: false
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    animCollapse: true,
                                    collapsed: true,
                                    collapsible: true,
                                    glyph: 'xf085@FontAwesome',
                                    hideCollapseTool: true,
                                    title: 'Maquinarias',
                                    titleAlign: 'left',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            flex: 1,
                                            header: false,
                                            title: 'My Grid Panel',
                                            autoLoad: true,
                                            forceFit: true,
                                            store: 'Labores_maquinaria',
                                            columns: [
                                                {
                                                    xtype: 'numbercolumn',
                                                    renderer: function(value, record, rowIndex) {
                                                        var store = Ext.getStore('MaquinariaMysql');
                                                        var num = store.find('codigo',value);
                                                        console.log(num);
                                                        if (num==-1) {return '...';}
                                                        else { return store.getAt(num).get('nombre');}
                                                    },
                                                    dataIndex: 'cod_maquina',
                                                    text: 'Cod Maquina',
                                                    format: '00'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'cantidad',
                                                    text: 'Cantidad',
                                                    format: '0'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    itemId: 'nuevoMaqPnl',
                                    animCollapse: true,
                                    collapseFirst: false,
                                    collapsed: true,
                                    collapsible: true,
                                    glyph: 'xf055@FontAwesome',
                                    hideCollapseTool: true,
                                    iconAlign: 'right',
                                    title: 'Nueva Maquinaria',
                                    titleAlign: 'right',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            flex: 0,
                                            itemId: 'maqCodigo',
                                            padding: '10px 20px',
                                            fieldLabel: '',
                                            editable: false,
                                            emptyText: 'Maquinaria',
                                            displayField: 'nombre',
                                            store: 'MaquinariaMysql',
                                            valueField: 'codigo'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            flex: 0,
                                            itemId: 'maqCantidad',
                                            padding: '10px 20px',
                                            fieldLabel: '',
                                            editable: false,
                                            emptyText: 'Cantidad'
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 0,
                                            margin: '',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    flex: 0,
                                                    flex: 0,
                                                    itemId: 'aceptaMaqLabBtn',
                                                    margin: '0px 10px',
                                                    text: 'Guardar'
                                                },
                                                {
                                                    xtype: 'button',
                                                    flex: 0,
                                                    flex: 0,
                                                    margin: '0px 10px',
                                                    text: 'Cancelar'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            tabBar: {
                xtype: 'tabbar',
                shadow: 'frame',
                id: 'maqTab',
                itemId: 'maqTab',
                modelValidation: false,
                rtl: false
            }
        },
        {
            xtype: 'toolbar',
            flex: 0,
            height: 60,
            itemId: 'laboresFoterTlb',
            style: 'background-color:#424242;',
            layout: {
                type: 'hbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    disabled: true,
                    itemId: 'aceptarLaboresbtn',
                    text: 'Aceptar'
                },
                {
                    xtype: 'button',
                    id: 'cancelBtn',
                    itemId: 'cancelBtn',
                    params: 'alert',
                    text: 'Cancelar'
                }
            ]
        }
    ]

});